services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CIRCLE_API_KEY=5283ee297b3b80890e8d2e63e526f99b:289087b8a83baeb0779b44aadeb55b40
      - CIRCLE_BASE_URL=https://api-sandbox.circle.com
      - PROCESSING_APP_URL=http://localhost:4000/api/process
    depends_on:
      - processing-app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  processing-app:
    build:
      context: ./processing-app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"